//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentdataContext : DbContext
    {
        public StudentdataContext()
            : base("name=StudentdataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnrollmentMaster> EnrollmentMasters { get; set; }
        public virtual DbSet<ServiceMaster> ServiceMasters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentEnrollment> StudentEnrollments { get; set; }
        public virtual DbSet<StudentService> StudentServices { get; set; }
    
        public virtual ObjectResult<sp_FetchStudentDetails_Result> sp_FetchStudentDetails(Nullable<int> studentId, Nullable<int> entrollmentId, Nullable<int> serviceId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var entrollmentIdParameter = entrollmentId.HasValue ?
                new ObjectParameter("EntrollmentId", entrollmentId) :
                new ObjectParameter("EntrollmentId", typeof(int));
    
            var serviceIdParameter = serviceId.HasValue ?
                new ObjectParameter("ServiceId", serviceId) :
                new ObjectParameter("ServiceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FetchStudentDetails_Result>("sp_FetchStudentDetails", studentIdParameter, entrollmentIdParameter, serviceIdParameter);
        }
    }
}
